# Generated by Django 3.0.7 on 2020-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200614_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailverification',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useremailverification',
            name='resent_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
