# Generated by Django 3.0.7 on 2020-06-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200616_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailverification',
            name='resent_at',
        ),
    ]
