# Generated by Django 3.0.7 on 2020-06-23 22:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_useremailverification_resent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 22, 12, 56, 307424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useremailverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
