image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Deploy
        services:
          - docker
        script:
          - curl  https://sdk.cloud.google.com
          - ls
          - cd ..
          - pwd
          - ls
          - cd ..
          - pwd
          - ls
            