image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Deploy
        services:
          - docker
        script:
          - curl  https://sdk.cloud.google.com | bash > /dev/null;
          - source ~/google-cloud-sdk/path.bash.inc
          - gcloud components update kubectl
          - echo $DEPLOY_KEY > deploy_key.json
          - gcloud auth activate-service-account --key-file deploy_key.json
          - gcloud config set project profiledev
          - gcloud config set compute/zone us-central1-c
          - gcloud container clusters get-credentials multi-cluster 
          - docker login -u _json_key -p "$GCR_KEY" https://gcr.io
          - docker pull profiledev/backend:latest
          - docker build -t profiledev/backend:latest



            