image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Deploy
        services:
          - docker
        script:
          - curl  https://sdk.cloud.google.com | bash > /dev/null;
          - source ~/google-cloud-sdk/path.bash.inc
          - gcloud components update kubectl



            