image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - pip
        services:
          - docker
        script:
          - export IMAGE_NAME=gcr.io/profiledev/backend:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          - docker login -u _json_key -p "$GCR_KEY" https://gcr.io
          - docker push $IMAGE_NAME
          - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          - chmod +x ./kubectl
          - mv ./kubectl /usr/local/bin/kubectl
          - kubectl apply k8s
          - python manage.py test
            