image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Deploy
        services:
          - docker
        script:
          - curl  https://sdk.cloud.google.com | bash > /dev/null;
          - source ~/google-cloud-sdk/path.bash.inc
          - gcloud components update kubectl
          - echo $OWNER_KEY > owner_key.json
          - gcloud auth activate-service-account --key-file owner_key.json
          - gcloud config set project profiledev
          - gcloud config set compute/zone us-central1-c
          - gcloud container clusters get-credentials multi-cluster 
          - docker login -u _json_key -p "$GCR_KEY" https://gcr.io
          - docker pull gcr.io/profiledev/backend:latest
          - docker build -t profile.dev/backend-test .
          - kubectl apply -f k8s
          - python managen.py test


            