image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Deploy
        image: google/cloud-sdk:latest
        services:
          - docker
        script:
          - curl  https://sdk.cloud.google.com | bash > /dev/null;
          - ls
            