image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - pip
        services:
          - docker
        script:
          - docker build -t backend:$BITBUCKET_COMMIT .
            