image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        script:
          - curl  https://sdk.cloud.google.com | bash > /dev/null;
          - source $HOME/google-cloud-sdk/path.bash.incafter-script
          - gcloud components update kubectl
          - gcloud auth activate-service-account --key-file $DEPLOY_KEY
            