image: python:3.7.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - pip
        services:
          - docker
        script:
          - pipe: atlassian/kubectl-run:1.1.2
            variables:
              KUBE_CONFIG: $KUBE_CONFIG
              KUBECTL_COMMAND: 'apply'
              RESOURCE_PATH: 'k8s'
          - pip install -r requirements.txt
          - "python manage.py test && flake8"  
    - step:
        name: Deploy
        script:
          - pipe: atlassian/google-app-engine-deploy:0.2.1
            variables:
              KEY_FILE: $KEY_FILE
              PROJECT: 'profiledev'