image: python:3.7.3

pipelines:
  default:
    - step:
        name: Test
        image:
          name: gcr.io/profiledev/backend:latest
          username: _json_key
          password: '$GCR_JSON_KEY'
        caches:
          - pip
        services:
          - docker
        script:
          - pipe: atlassian/kubectl-run:1.1.8
            variables:
              KUBE_CONFIG: $KUBE_CONFIG
              KUBECTL_COMMAND: 'apply'
              RESOURCE_PATH: 'k8s'
          - "python manage.py test && flake8"