image: python:3.7.3
options:
  docker: true
pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - pip
        services:
          - docker
        script:
          - export IMAGE_NAME=gcr.io/profiledev/backend:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          - docker login -u _json_key -p "$GCR_KEY" https://gcr.io
          - docker push $IMAGE_NAME
          - python manage.py test && flake8
            