version: '3'

services:
 app_migrate:
   build:
     context: .
   command:
     ["python", "manage.py", "migrate"]
   environment:
     - DB_HOST=db
     - DB_PORT=5432
     - DB_NAME=profile_dev
     - DB_USER=profile_dev
     - DB_PASS=profile_dev
   depends_on:
     - db

 app_celery_worker:
   build:
     context: .
   command:
     ["celery", "-A", "profile_dev", "worker", "-l", "info"]
   environment:
     - DB_HOST=db
     - DB_PORT=5432
     - DB_NAME=profile_dev
     - DB_USER=profile_dev
     - DB_PASS=profile_dev
   depends_on:
     - redis

 app_celery_beat:
   build:
     context: .
   command:
     ["celery", "-A", "profile_dev", "beat", "-l", "info"]
   environment:
     - DB_HOST=db
     - DB_PORT=5432
     - DB_NAME=profile_dev
     - DB_USER=profile_dev
     - DB_PASS=profile_dev
   depends_on:
     - redis

 app:
   build:
     context: .
   ports:
     - "8000:8000"
   command:
     ["python", "manage.py", "runserver", "0.0.0.0:8000"]
   environment:
     - DB_HOST=db
     - DB_PORT=5432
     - DB_NAME=profile_dev
     - DB_USER=profile_dev
     - DB_PASS=profile_dev
   depends_on:
     - app_migrate
     - db
     - redis


 db:
   image: postgres:10-alpine
   environment: 
    - POSTGRES_DB=profile_dev
    - POSTGRES_USER=profile_dev
    - POSTGRES_PASSWORD=profile_dev
    - POSTGRES_PORT=5432

 redis:
   image: redis:alpine
   ports:
      - 6379:6379
