apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api-cluster-ip-service"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 8000
      targetPort: 8000