# Generated by Django 3.0.7 on 2020-07-02 10:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='media/uploads/avatar/download.jpeg', upload_to=user_profile.models.avatar_image_file_path)),
                ('job_experiences', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None), blank=True, default=None, null=True, size=None)),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None), blank=True, default=None, null=True, size=None)),
                ('certifications', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None), blank=True, default=None, null=True, size=None)),
                ('about', models.TextField(default=None, null=True)),
                ('social_info', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None), blank=True, default=None, null=True, size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=None, null=True, size=None)),
            ],
        ),
    ]
