apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  db_password: {{ .Values.db_password | b64enc | quote }}
  email_host_password: {{ .Values.email_host_password | b64enc | quote }}